name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yarn install 
    - name: Run Build
      run: |
        yarn run build
    - name: Validate Build
      run: |
        cat dist/index.html > /dev/null
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: dist